### ISSUE TITLE
Build compilation issues - affects NPM 0.0.13

### ISSUE THREAD

**Issue by BradfordMedeiros** [js-accounts/accounts#102]
Currently if you look at 0.0.13 the onResumedSessionHook is in lib-es6 but not in lib, meaning somewhere in the build process something went wrong. 

Rebuilding off of master gives the correct results with the new code being in both.
Could be a variety of errors, but putting the issue up here for visibility.

Best solution imo would be to recompile and deploy bumped version to npm to get a good release out, and then look into the build issues as time allows.

Thanks guys.  Cool library. 

@davidyaha @TimMikeladze

**Comment by davidyaha** [comment]
Thanks for the report! @TimMikeladze published a new version so it is fixed now.
We should leave this one open until the publish script has been taken a look at.
Probably a good direction would be to use `rimraf` package and clean the lib dirs before compiling.

**Comment by davidyaha** [comment]
Closed with https://github.com/js-accounts/accounts/commit/01376512a696d0972a9e1329dfabc4a29981024c
