### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TimMikeladze** [js-accounts/accounts#11]
@gadicc What are you thinking our approach should be for documentation?

I'm thinking we could standup a static site similar to http://dev.apollodata.com/tools/

**Comment by matteodem** [comment]
Would be awesome to have some docs regarding this library. https://surge.sh/ allows to host the static page for free

**Comment by gadicc** [comment]
@matteodem thanks for the link.  The package is still in very early development so no docs yet... we'll put more detailed instructions up in the README once the package is more useable, but yes, we'd love to have some static docs as @TimMikeladze mentioned in the longer term.

**Comment by TimMikeladze** [comment]
Here's an possible solution https://github.com/documentationjs/documentation

**Comment by TimMikeladze** [comment]
Bonus points: documentationjs plays well with Flow.

**Comment by pradel** [comment]
Another possible solution https://github.com/gatsbyjs/gatsby

**Comment by pradel** [comment]
A hosting solution https://www.netlify.com/ (they have a free open source plan that generate the static site on git push)

**Comment by TimMikeladze** [comment]
Closing this issue as it's on going here https://github.com/js-accounts/docs
