### ISSUE TITLE
Schedule a community meeting! 🦁🐯🦄

### ISSUE THREAD

**Issue by davidyaha** [js-accounts/accounts#117]
Hello to everyone involved / using this project!

I am David, one of the cotributors to this project and I would like to propose a video call to allow everyone to get to know each other and maybe, (if lucky) form a clear roadmap for this project.

I am personally very invested in this project as I am using it constantly in all of the projects I am working on, so I would love to see and meet whoever else that has any interest in this cool project!

Anyone interested, please use this doodle to vote on time in the next two weeks: https://doodle.com/poll/gz6rbygtuvka5x98

Any comments or suggestions are welcome!

Thanks!

**Comment by TimMikeladze** [comment]
Digging the initiative, let's get it done!

**Comment by davidyaha** [comment]
@TimMikeladze @pradel @darkbasic @Aetherall

The days that will be okay with everyone are:
- Thu, Nov 9th
- Mon, Nov 13th
- Wed, Nov 15th
- Thu, Nov 16th

Which timing will be best and will it work out this Thursday:
- 12:00 UTC+2 - 12:30 UTC+2
- 17:00 UTC+2 - 18:30 UTC+2
- 19:00 UTC+2 - 20:30 UTC+2

Let me know and please send me your email address so i'll send an invite.
Mine is on my github profile.

**Comment by darkbasic** [comment]
I prefer 17:00 UTC+2 - 18:30 UTC+2. Thursday is fine for me.
My email address is on my github profile, but I'm sending you an email anyway.

**Comment by pradel** [comment]
Thursday is perfect and all timings works for me :)

**Comment by TimMikeladze** [comment]
Thursday is good for me.

17:00 UTC + 2 - 18:30 UTC + 2

OR 

19:00 UTC + 2 - 20:30 UTC + 2

**Comment by davidyaha** [comment]
Great! Sent everyone an invite! 
Note that there is a google hangouts on the event.

I've created a small start of an agenda and goals doc - https://docs.google.com/document/d/18pQP5FWXGDLY21g7TNnrEz6-88cBAXr5wRWnzvxbDwE/edit?usp=sharing

**Feel free to edit it as you wish!** 🔈

**Comment by davidyaha** [comment]
@TimMikeladze @darkbasic @Aetherall
https://hangouts.google.com/hangouts/_/b5vkzhhclneohn67bdxmgaos7ye

**Comment by darkbasic** [comment]
I'm sorry but for some reason I didn't receive the google calendar notifications.
I tried to connect at 17:30 after I got the github notification, but it seems it was already too late.
Do someone have a recording of the meeting?

**Comment by davidyaha** [comment]
Sorry to hear that @darkbasic! I don't have any, maybe someone else.. 
I've added you now to the hangouts so we can speak in a chat environment.
We've updated the doc with the gist of what we plan on doing so definitely take a look and let us know what your thoughts!

Hope to see you next time in about two weeks!
