### ISSUE TITLE
Typing system

### ISSUE THREAD

**Issue by TimMikeladze** [js-accounts/accounts#21]
Per discussion with @davidyaha, this set of packages could benefit from a typing system since we're defining interfaces for communication between packages. 

Flow and Typescript are the two options. I like Flow in favor of Typescript because of the minimal buy in, you can continue using the current build setup which is more familiar for JS developers not familiar with Typescript. On the other hand, Typescript has been gaining a considerable amount of adoption in the community but does have a more involved configuration.

**Comment by davidyaha** [comment]
Started working on the GraphQL transport with flow. If there is strong objection to it, let us know.
