### ISSUE TITLE
Rewrite / Improve error handling

### ISSUE THREAD

**Issue by TimMikeladze** [js-accounts/accounts#31]
Currently the `apollo-errors` package is being consumed by our custom `AccountsError` class to throw errors. Moving forward we can continue using `apollo-errors` or make our own custom error class. The reason behind using `apollo-errors` is that it allows errors to carry more data than just an error message, this is particularly useful in the case of validation errors where you want to associate errors with certain fields. Furthermore this allows http status codes to be sent along side the message, rather than within it. 

The other packages that consume `@accounts/accounts`: `rest-api`, `rest`, `react` and the db interfaces will also need their error handling code to be updated as part of this issue.

**Comment by TimMikeladze** [comment]
@davidyaha Maybe you could tackle this issue?

**Comment by davidyaha** [comment]
On vacation till Monday but I'll take a look when I get back. Rest-example is currently working?

**Comment by TimMikeladze** [comment]
Yep, on the `devel` branch with redis as the data store. It's working, will be working even better by Monday 😜 , dedicating the entire weekend to this.

**Comment by davidyaha** [comment]
Nice! Have fun!
