### ISSUE TITLE
Mock net and dns modules if running in browser 

### ISSUE THREAD

**Issue by TimMikeladze** [js-accounts/accounts#32]
@davidyaha per our discussion in slack 

The https://github.com/auth0/node-jsonwebtoken package has dependencies on the net and dns modules which aren't available on the client. This presents a problem since this is a repo publishing both client and server code in a single package. 

Currently the work around is to mock them in the consuming app's webpack config as seen below. 

```javascript
node: {
    net: 'mock',
    dns: 'mock',
  },
```

The simple solution is to provide these mocks within the core accounts package if running on the browser.

**Comment by davidyaha** [comment]
I've looked into it and we might want to setup lerna for the accounts package only. What do you think?

**Comment by TimMikeladze** [comment]
Fine by me. But I don't see how this will fix the problem unless the solution ends up being to split this repo up into a client and server repo?

**Comment by davidyaha** [comment]
The repo will stay a mono repo but lerna will create at least two packages on npm. I think actually we need three packages: core, server and client.
Using lerna these packages will carry the same version number and we can do treeshaking for each of these separately. 
We could actually manage the whole "suites" deal this way.. but this is for later time.

**Comment by TimMikeladze** [comment]
This will be resolved by #33
