### ISSUE TITLE
Setup Lerna and rearrange / rename repos

### ISSUE THREAD

**Issue by TimMikeladze** [js-accounts/accounts#33]
Setup [Lerna ](https://github.com/lerna/lerna). This task needs to be completed before an official release of the packages.

I suspect the repos and packages will look like this:

**accounts**
- `@accounts/core`
- `@accounts/client`
- `@accounts/server`

**rest**
- `@accounts/rest-client`
- `@accounts/rest-express`
- `@accounts/rest-koa`
- `@accounts/rest-hapi`

**graphql**
- `@accounts/graphql-client`
- `@accounts/graphql-express`
- `@accounts/graphql-koa`
- `@accounts/graphql-hapi`

**react**
- `@accounts/react`
- `@accounts/react-material-ui`

**Comment by davidyaha** [comment]
Yep I think it's a good layout. Multiple repos still has its benefits, but different build flavours will be managed by lerna.
