### ISSUE TITLE
Sensible data export

### ISSUE THREAD

**Issue by pradel** [js-accounts/accounts#56]
Right now [here](https://github.com/js-accounts/accounts/blob/master/packages/server/src/AccountsServer.js#L179) we export the all user object so the bcrypt token etc are sent back to the user.

**Comment by TimMikeladze** [comment]
Could you please elaborate on this issue?

**Comment by pradel** [comment]
We need to limit the user object returned to the client. Right now the bcrypted password is sent to the client in the user object which is not secure.

**Comment by TimMikeladze** [comment]
Woah seriously? I'll fix that right away.

**Comment by TimMikeladze** [comment]
This issue is tracked here https://github.com/js-accounts/mongo/issues/16
