### ISSUE TITLE
Authorisation and redux-auth-wrapper

### ISSUE THREAD

**Issue by jmatsushita** [js-accounts/accounts#6]
Hi again,

I was wondering if you were thinking of integrating something like `redux-auth-wrapper` which is a really nice HOC from @mjrussell that integrates well with react-router (and react-router-redux as shown [here](https://github.com/mjrussell/react-redux-jwt-auth-example/tree/react-router-redux)) or if you had something else in mind for authorisation?

Cheers,

Jun

**Comment by TimMikeladze** [comment]
Great suggestion! I'm working on this right now, will take a look at that package.

**Comment by mjrussell** [comment]
Happy to help if you have any questions or run into any stumbling blocks!

**Comment by TimMikeladze** [comment]
Closing this issue as it's being handle by our set of packages.
